name: CI
on:
  pull_request:
  push:

jobs:
  test:
    name: Test Suite
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup update stable && rustup default stable

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test

  readme:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.repository == 'loiccoyle/strandify' && github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Install toolchain
        run: rustup update stable && rustup default stable

      - uses: Swatinem/rust-cache@v2

      - run: make readme
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(readme): update help message"
          branch: ${{ github.head_ref }}
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
